dataset: mnist
trainer: auto
evaluators: []

batch_size: 512
accumulation_steps: 1

epochs: 300
eval_every: 1

heads:
  - kind: coral
    name: coral-1
    args:
      num_classes: 10
  - kind: classification
    name: xe-1
    args:
      num_classes: 10

losses:
  - kind: coral
    name: coral-1
    target_head: coral-1
    args:
      num_classes: 10

  - kind: xe
    name: xe-1
    target_head: xe-1
    args:
      num_classes: 10


lr_scheduler:
  start_epoch: 0
  end_epoch: 200
  base_lr: 0.0001
  max_lr:  0.001
  mode: triangular
  step_size_up: 10
  step_size_down: 10

model: mnist-cnn
model_args:
  embedding_size: 128
